CREATE TABLE threads (
    id SERIAL PRIMARY KEY,
    board_id INT REFERENCES boards(id) ON DELETE CASCADE,
    topic TEXT NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT NOW(),
    locked BOOLEAN NOT NULL DEFAULT(FALSE)
)